# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
import datetime
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator
from PyQt5 import QtCore, QtGui, QtWidgets
from P_02_SETTING import Ui_P_02_SETTING


class Ui_P_01(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 769)
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 20, 1321, 701))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 640, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("#pushButton_5 {color: rgb(0, 0, 0);background:None;background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(198, 198, 198), stop:1  rgb(255, 255, 255));border-radius:20px;border-color: rgb(0, 0, 0);border-style:outset;border-width:1px;}#pushButton_5:hover {border: 1px solid green; color: rgb(0, 255, 0);background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(255, 255, 255), stop:1  rgb(198, 198, 198));padding-bottom: 5px;padding-right: 5px;}#pushButton_5:pressed {background-color: rgb(255, 255, 255);padding-top: 5px;padding-left: 5px;}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(290, 640, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("#pushButton_6 {background:None;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(37, 197, 255), stop:1  rgb(44, 69, 211));\n"
"    \n"
"    \n"
"border-radius:20px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width:1px;\n"
"}\n"
"#pushButton_6:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(44, 69, 211), stop:1  rgb(37, 197, 255));\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"#pushButton_6:pressed {\n"
"background-color: rgb(37, 197, 255);\n"
"padding-top: 5px;\n"
"padding-left: 5px;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(1170, 640, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("#pushButton_7 {background:None;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(255, 0, 0), stop:1  rgb(255, 114, 114));\n"
"    \n"
"    \n"
"border-radius:20px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width:1px;\n"
"}\n"
"#pushButton_7:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(255, 114, 114), stop:1  rgb(255, 0, 0));\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"#pushButton_7:pressed {\n"
"background-color: rgb(255, 255, 255);\n"
"padding-top: 5px;\n"
"padding-left: 5px;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(20, 220, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("")
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(180, 220, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(170, 640, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("#pushButton_8 {color: rgb(255, 0, 0);background:None;background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(255, 255, 255), stop:1  rgb(198, 198, 198));border-radius:20px;border-color: rgb(0, 0, 0);border-style:outset;border-width:1px;}#pushButton_8:hover { border: 1px solid red;color: rgb(0, 0, 0);background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(198, 198, 198), stop:1  rgb(255, 255, 255));padding-bottom: 5px;padding-right: 5px;}#pushButton_8:pressed {background-color: rgb(198, 198, 198);padding-top: 5px;padding-left: 5px;}\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(30, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 310, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(20, 260, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(180, 260, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber.setGeometry(QtCore.QRect(20, 80, 381, 121))
        self.lcdNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber.setLineWidth(3)
        self.lcdNumber.setProperty("value", 20000.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_47 = QtWidgets.QLabel(self.frame)
        self.label_47.setGeometry(QtCore.QRect(1020, 90, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(180, 320, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("border:1px solid black;\n"
"border-radius: 10px;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_10.setGeometry(QtCore.QRect(140, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("#pushButton_10 {background:None;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(37, 197, 255), stop:1  rgb(44, 69, 211));\n"
"    \n"
"    \n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width:1px;\n"
"}\n"
"#pushButton_10:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(44, 69, 211), stop:1  rgb(37, 197, 255));\n"
"padding-bottom: 3px;\n"
"padding-right: 3px;\n"
"}\n"
"\n"
"#pushButton_10:pressed {\n"
"background-color: rgb(37, 197, 255);\n"
"padding-top: 5px;\n"
"padding-left: 5px;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(20, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        reg_ex = QRegExp("\\d+\\.\\d+")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_8)
        self.lineEdit_8.setValidator(input_validator)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_56 = QtWidgets.QLabel(self.frame)
        self.label_56.setGeometry(QtCore.QRect(20, 10, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("color: rgb(0, 85, 127);")
        self.label_56.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_56.setObjectName("label_56")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(410, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_2.setGeometry(QtCore.QRect(530, 80, 381, 121))
        self.lcdNumber_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_2.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_2.setLineWidth(3)
        self.lcdNumber_2.setProperty("value", 20000.0)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(930, 170, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("")
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setGeometry(QtCore.QRect(640, 330, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("border:1px solid black;\n"
"border-radius: 10px;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_11.setGeometry(QtCore.QRect(130, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("#pushButton_11 {background:None;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(37, 197, 255), stop:1  rgb(44, 69, 211));\n"
"    \n"
"    \n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width:1px;\n"
"}\n"
"#pushButton_11:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(44, 69, 211), stop:1  rgb(37, 197, 255));\n"
"padding-bottom: 3px;\n"
"padding-right: 3px;\n"
"}\n"
"\n"
"#pushButton_11:pressed {\n"
"background-color: rgb(37, 197, 255);\n"
"padding-top: 5px;\n"
"padding-left: 5px;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(20, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit_9.setFont(font)
        reg_ex = QRegExp("\\d+\\.\\d+")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_9)
        self.lineEdit_9.setValidator(input_validator)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_3.setGeometry(QtCore.QRect(530, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_4.setGeometry(QtCore.QRect(530, 320, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.label_48 = QtWidgets.QLabel(self.frame)
        self.label_48.setGeometry(QtCore.QRect(1090, 10, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color: rgb(170, 0, 255);")
        self.label_48.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setGeometry(QtCore.QRect(540, 640, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("#pushButton_9 {background:None;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(0, 255, 0), stop:1  rgb(124, 250, 128));\n"
"    \n"
"\n"
"border-radius:20px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width:1px;\n"
"}\n"
"#pushButton_9:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(124, 250, 128), stop:1  rgb(0, 255, 0));\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"#pushButton_9:pressed {\n"
"background-color: rgb(255, 255, 255);\n"
"padding-top: 5px;\n"
"padding-left: 5px;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(30, 420, 411, 191))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(0, 3, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.line_18 = QtWidgets.QFrame(self.frame)
        self.line_18.setGeometry(QtCore.QRect(460, 0, 20, 701))
        self.line_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_18.setLineWidth(3)
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setObjectName("line_18")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_2.setGeometry(QtCore.QRect(530, 420, 401, 191))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_2.setItem(0, 3, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(530, 230, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("")
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(530, 270, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(690, 270, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(690, 230, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.line_19 = QtWidgets.QFrame(self.frame)
        self.line_19.setGeometry(QtCore.QRect(970, 0, 20, 721))
        self.line_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_19.setLineWidth(3)
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setObjectName("line_19")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_3.setGeometry(QtCore.QRect(1020, 160, 281, 451))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_3.setItem(0, 1, item)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("MainWindow", "Start"))
        self.pushButton_6.setText(_translate("MainWindow", "Report"))
        self.pushButton_7.setText(_translate("MainWindow", "Close"))
        self.label_20.setText(_translate("MainWindow", "Last Transaction Id:"))
        self.label_19.setText(_translate("MainWindow", "10001"))
        self.pushButton_8.setText(_translate("MainWindow", "Stop"))
        self.radioButton.setText(_translate("MainWindow", "Auto"))
        self.radioButton_2.setText(_translate("MainWindow", "Manual"))
        self.label_26.setText(_translate("MainWindow", "Last  Material:"))
        self.label_30.setText(_translate("MainWindow", "CD-1001"))
        self.label_47.setText(_translate("MainWindow", "Live Stock - (Kg.)"))
        self.pushButton_10.setText(_translate("MainWindow", "Update"))
        self.label_56.setText(_translate("MainWindow", "Running.."))
        self.label_15.setText(_translate("MainWindow", "Kg."))
        self.label_17.setText(_translate("MainWindow", "Kg."))
        self.pushButton_11.setText(_translate("MainWindow", "Update"))
        self.radioButton_3.setText(_translate("MainWindow", "Auto"))
        self.radioButton_4.setText(_translate("MainWindow", "Manual"))
        self.label_48.setText(_translate("MainWindow", "05 Aug 2020 14:23"))
        self.pushButton_9.setText(_translate("MainWindow", "Setting"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Transaction Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Material"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Weight(Kg)"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Timestamp"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        # item = self.tableWidget.item(0, 0)
        # item.setText(_translate("MainWindow", "30221"))
        # item = self.tableWidget.item(0, 1)
        # item.setText(_translate("MainWindow", "CD-10023"))
        # item = self.tableWidget.item(0, 2)
        # item.setText(_translate("MainWindow", "98.560"))
        # item = self.tableWidget.item(0, 3)
        # item.setText(_translate("MainWindow", "22-11-2011 03:44:55"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Transaction Id"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Material"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Weight(Kg)"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Timestamp"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        # item = self.tableWidget_2.item(0, 0)
        # item.setText(_translate("MainWindow", "30222"))
        # item = self.tableWidget_2.item(0, 1)
        # item.setText(_translate("MainWindow", "CD-1020"))
        # item = self.tableWidget_2.item(0, 2)
        # item.setText(_translate("MainWindow", "98.560"))
        # item = self.tableWidget_2.item(0, 3)
        # item.setText(_translate("MainWindow", "22-11-2011 03:44:55"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_21.setText(_translate("MainWindow", "Last Transaction Id:"))
        self.label_27.setText(_translate("MainWindow", "Last  Material:"))
        self.label_31.setText(_translate("MainWindow", "CD-1001"))
        self.label_22.setText(_translate("MainWindow", "10001"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Material"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Live Stock (Kg)"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("MainWindow", "CD-1020"))
        item = self.tableWidget_3.item(0, 1)
        item.setText(_translate("MainWindow", "987676787678.560"))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.timer=QtCore.QTimer()
        self.timer.start(1)
        self.timer.setInterval(1000)
        self.timer.timeout.connect(self.deviceDateTime)
        self.pushButton_7.clicked.connect(MainWindow.close)
        self.lineEdit_8.setDisabled(True)
        self.lineEdit_9.setDisabled(True)
        self.pushButton_11.setDisabled(True)
        self.label_56.hide()
        self.loadData()
        self.pushButton_9.clicked.connect(self.openSetting)
        self.pushButton_10.clicked.connect(self.update_Device1_data)
        self.pushButton_11.clicked.connect(self.update_Device2_data)
        self.radioButton_2.clicked.connect(self.toggelRadioBtn_sec1)
        self.radioButton.clicked.connect(self.toggelRadioBtn_sec1)
        self.radioButton_3.clicked.connect(self.toggelRadioBtn_sec2)
        self.radioButton_4.clicked.connect(self.toggelRadioBtn_sec2)
    def deviceDateTime(self):
        self.label_48.setText(datetime.datetime.now().strftime("%d %b %Y %H:%M:%S"))    
    def loadData(self):
        connection = sqlite3.connect('WT_P.db')
        c = connection.cursor()
        c.execute("SELECT ID, MATERIAL_NAME, WEIGHT, CREATED_ON FROM TRANSACTION_MST ORDER BY CREATED_ON DESC LIMIT 50")
        rows = c.fetchall()
        
        # Set row counts for both table widgets
        self.tableWidget.setRowCount(len(rows))
        self.tableWidget_2.setRowCount(len(rows))
        
        # Populate tableWidget
        for row_number, row_data in enumerate(rows):
                for column_number, col_data in enumerate(row_data):
                        item = QtWidgets.QTableWidgetItem(str(col_data))
                        # Set font size
                        font = QtGui.QFont()
                        font.setPointSize(10)  
                        item.setFont(font)
                        self.tableWidget.setItem(row_number, column_number, item)
        
        # Populate tableWidget_2
        for row_number, row_data in enumerate(rows):
                for column_number, col_data in enumerate(row_data):
                        item = QtWidgets.QTableWidgetItem(str(col_data))
                        # Set font size
                        font = QtGui.QFont()
                        font.setPointSize(10)  
                        item.setFont(font)
                        self.tableWidget_2.setItem(row_number, column_number, item)
        
        # Fetch the last ID and update the label
        c.execute("SELECT MAX(ID) FROM TRANSACTION_MST")
        last_id = c.fetchone()[0]
        if last_id is None:
                last_id = 0  # If no data in the table, start from 0
        self.label_19.setText(str(last_id + 1))
        self.label_22.setText(str(last_id + 1))
        
        connection.close()

    def update_Device1_data(self):
        
        connection = sqlite3.connect('WT_P.db')
        c = connection.cursor()
        
        if self.radioButton.isChecked():
                self.label_56.hide()
                c.execute(
                        "INSERT INTO TRANSACTION_MST (MATERIAL_CODE, MATERIAL_NAME, WEIGHT, CREATED_ON, DEVICE_ID, TRANSACTION_TYPE) VALUES (?, ?, ?, datetime('now'), ?, ?)",
                        (self.label_30.text(), self.label_30.text(), float(self.lcdNumber.value()), 1, "AUTO" )
                )
                connection.commit()
                c.execute("SELECT ID, MATERIAL_NAME, WEIGHT, CREATED_ON FROM TRANSACTION_MST ORDER BY CREATED_ON DESC LIMIT 50")

                rows = c.fetchall()
                # Set row counts for table widgets
                self.tableWidget.setRowCount(len(rows))
               
                
                # Populate tableWidget
                for row_number, row_data in enumerate(rows):
                        for column_number, col_data in enumerate(row_data):
                                item = QtWidgets.QTableWidgetItem(str(col_data))
                                # Set font size
                                font = QtGui.QFont()
                                font.setPointSize(10)  
                                item.setFont(font)
                                self.tableWidget.setItem(row_number, column_number, item)
                
                # Fetch the last ID and update the label
                c.execute("SELECT MAX(ID) FROM TRANSACTION_MST")
                last_id = c.fetchone()[0]
                if last_id is None:
                        last_id = 0  # If no data in the table, start from 0
                self.label_19.setText(str(last_id + 1))
                self.label_22.setText(str(last_id + 1))
                
        elif self.radioButton_2.isChecked():
            if (self.lineEdit_8.text() != ''):
                self.lcdNumber.display(float(self.lineEdit_8.text()))
                c.execute(
                        "INSERT INTO TRANSACTION_MST (MATERIAL_CODE, MATERIAL_NAME, WEIGHT, CREATED_ON, DEVICE_ID, TRANSACTION_TYPE) VALUES (?, ?, ?, datetime('now'), ?, ?)",
                        (self.label_30.text(), self.label_30.text(), float(self.lineEdit_8.text()), 1, "MANUAL" )
                )
                connection.commit()
                c.execute("SELECT ID, MATERIAL_NAME, WEIGHT, CREATED_ON FROM TRANSACTION_MST ORDER BY CREATED_ON DESC LIMIT 50")

                rows = c.fetchall()
                # Set row counts for table widgets
                self.tableWidget.setRowCount(len(rows))
        
                
                # Populate tableWidget
                for row_number, row_data in enumerate(rows):
                        for column_number, col_data in enumerate(row_data):
                                item = QtWidgets.QTableWidgetItem(str(col_data))
                                # Set font size
                                font = QtGui.QFont()
                                font.setPointSize(10)  
                                item.setFont(font)
                                self.tableWidget.setItem(row_number, column_number, item)
                
        
                # Fetch the last ID and update the label
                c.execute("SELECT MAX(ID) FROM TRANSACTION_MST")
                last_id = c.fetchone()[0]
                if last_id is None:
                        last_id = 0  # If no data in the table, start from 0
                self.label_19.setText(str(last_id + 1))
                self.label_22.setText(str(last_id + 1))
            else:
                self.label_56.setText("Please enter the weight")
                self.label_56.show()
            
    
    def update_Device2_data(self):
        
        connection = sqlite3.connect('WT_P.db')
        c = connection.cursor()
        
        if self.radioButton_3.isChecked():
                self.label_56.hide()
                c.execute(
                        "INSERT INTO TRANSACTION_MST (MATERIAL_CODE, MATERIAL_NAME, WEIGHT, CREATED_ON, DEVICE_ID, TRANSACTION_TYPE) VALUES (?, ?, ?, datetime('now'), ?, ?)",
                        (self.label_30.text(), self.label_30.text(), float(self.lcdNumber_2.value()), 2, "AUTO" )
                )
                connection.commit()
                c.execute("SELECT ID, MATERIAL_NAME, WEIGHT, CREATED_ON FROM TRANSACTION_MST ORDER BY CREATED_ON DESC LIMIT 50")

                rows = c.fetchall()
                # Set row counts for table widgets
                self.tableWidget_2.setRowCount(len(rows))
               
                
                # Populate tableWidget
                for row_number, row_data in enumerate(rows):
                        for column_number, col_data in enumerate(row_data):
                                item = QtWidgets.QTableWidgetItem(str(col_data))
                                # Set font size
                                font = QtGui.QFont()
                                font.setPointSize(10)  
                                item.setFont(font)
                                self.tableWidget_2.setItem(row_number, column_number, item)

                # Fetch the last ID and update the label
                c.execute("SELECT MAX(ID) FROM TRANSACTION_MST")
                last_id = c.fetchone()[0]
                if last_id is None:
                        last_id = 0  # If no data in the table, start from 0
                self.label_19.setText(str(last_id + 1))
                self.label_22.setText(str(last_id + 1))
                
        elif self.radioButton_4.isChecked():
            if (self.lineEdit_9.text() != ''):
                self.lcdNumber_2.display(float(self.lineEdit_9.text()))
                c.execute(
                        "INSERT INTO TRANSACTION_MST (MATERIAL_CODE, MATERIAL_NAME, WEIGHT, CREATED_ON, DEVICE_ID, TRANSACTION_TYPE) VALUES (?, ?, ?, datetime('now'), ?, ?)",
                        (self.label_30.text(), self.label_30.text(), float(self.lineEdit_9.text()), 2, "MANUAL" )
                )
                connection.commit()
                c.execute("SELECT ID, MATERIAL_NAME, WEIGHT, CREATED_ON FROM TRANSACTION_MST ORDER BY CREATED_ON DESC LIMIT 50")

                rows = c.fetchall()
                # Set row counts for table widgets
                self.tableWidget_2.setRowCount(len(rows))
        
                
                # Populate tableWidget
                for row_number, row_data in enumerate(rows):
                        for column_number, col_data in enumerate(row_data):
                                item = QtWidgets.QTableWidgetItem(str(col_data))
                                # Set font size
                                font = QtGui.QFont()
                                font.setPointSize(10)  
                                item.setFont(font)
                                self.tableWidget_2.setItem(row_number, column_number, item)
                
        
                # Fetch the last ID and update the label
                c.execute("SELECT MAX(ID) FROM TRANSACTION_MST")
                last_id = c.fetchone()[0]
                if last_id is None:
                        last_id = 0  # If no data in the table, start from 0
                self.label_19.setText(str(last_id + 1))
                self.label_22.setText(str(last_id + 1))
            else:
                self.label_56.setText("Please enter the weight")
                self.label_56.show()
                          
     
        

    def toggelRadioBtn_sec1(self):
        if self.radioButton_2.isChecked():
            self.lineEdit_8.setEnabled(True)
            self.lineEdit_9.setDisabled(True)
            self.pushButton_11.setDisabled(True)
            self.pushButton_10.setEnabled(True)
            self.label_56.hide()

        else:
            self.lineEdit_8.setDisabled(True)
            self.lineEdit_9.setDisabled(True)
            self.pushButton_11.setDisabled(True)
            self.pushButton_10.setEnabled(True)
            self.label_56.hide()


    def toggelRadioBtn_sec2(self):
        if self.radioButton_4.isChecked():
            self.pushButton_11.setEnabled(True)    
            self.lineEdit_9.setEnabled(True)
            self.lineEdit_8.setDisabled(True)
            self.pushButton_10.setDisabled(True)
            self.label_56.hide()

        else:
            self.pushButton_11.setEnabled(True)
            self.lineEdit_9.setDisabled(True)
            self.lineEdit_8.setDisabled(True)
            self.pushButton_10.setDisabled(True)
            self.label_56.hide()

    def openSetting(self):
        self.window = QtWidgets.QMainWindow()
        self.ui=Ui_P_02_SETTING()
        self.ui.setupUi(self.window)           
        self.window.show()         


    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_P_01()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
